name: Vasudev Bongale
bio: Platform engineer. Sanskrit student. Occasional mountaineer.
role: Engineer @LinkedIn
url: https://vasudevb.com

permalink: /writing/:year/:month/:title
markdown: kramdown

exclude:
  - README.md
  - DEVELOPMENT.md
  - Gemfile
  - Gemfile.lock
  - vendor

github: vasudev-bongale
linkedin: vasudevbongale

plugins:
  - jekyll-seo-tag
